enum FILE_MENU {
	FILE_NEW,
	FILE_OPEN,
	FILE_COPY,
	FILE_COPY_LIGHT,
	FILE_COPY_DARK,
	FILE_RENAME,
	FILE_DUPLICATE,
	FILE_MOVE_DUPLICATE,
	FILE_DELETE,
	PATH_COPY,
	GROUP_EXPAND_ALL,
	GROUP_COLLAPSE_ALL,
	COLOR_NEW,
	DUAL_NEW,
	GROUP_NEW,
}

const DEFAULT_COLOR = Color.BLACK

const COLOR_SYSTEM_PREFIX := "pal"
const COLOR_POPUP_ID := "COLOR_POPUP_ID"
const NUMBER_POPUP_ID := "NUMBER_POPUP_ID"
